from shop.models import Item, Purchase
from django.utils import timezone

item_1 = Item(name="laptop", price=500)
item_1.save()
item_2 = Item(name='smartphone', price=400)
item_2.save()
item_3 = Item(name='mouse', price=50)
item_3.save()
item_4 = Item(name='headset', price=100)
item_4.save()
item_5 = Item(name='charger', price=75)
item_5.save()

p1 = Purchase(name="Aibek", age=36, date_purchase=timezone.now(), item=item_1)
p1.save()
p2 = Purchase(name="Ermek", age=32, date_purchase=timezone.now(), item=item_1)
p2.save()
p3 = Purchase(name="Aijan", age=29, date_purchase=timezone.now(), item=item_2)
p3.save()
p4 = Purchase(name="Cholpon", age=32, date_purchase=timezone.now(), item=item_2)
p4.save()
p5 = Purchase(name="Bermet", age=25, date_purchase=timezone.now(), item=item_3)
p5.save()
p6 = Purchase(name="Nursultan", age=27, date_purchase=timezone.now(), item=item_3)
p6.save()
p7 = Purchase(name="Manas", age=45, date_purchase=timezone.now(), item=item_4)
p7.save()
p8 = Purchase(name="Jibek", age=20, date_purchase=timezone.now(), item=item_4)
p8.save()
p9 = Purchase(name="Azat", age=35, date_purchase=timezone.now(), item=item_5)
p9.save()
p10 = Purchase(name="Uluk", age=35, date_purchase=timezone.now(), item=item_5)
p10.save()